### ISSUE TITLE
Call to a member function table() on null

### ISSUE THREAD

**Issue by milad4444** [shayan100/IraninaDatePicker-filament#2]
when i use **_IranianDatePickerColumn::make('created_at')->format('Y/m/d'),_**
this error display
**Call to a member function table() on null**

**Comment by shayan-yousefi** [comment]
Hi Milad, I have no access to my system I will check it soon.

**Comment by shayan-yousefi** [comment]
I think this error was displayed because your created_at is null in the database.

But I will check it when I accessed my system to fix this bug.

**Comment by milad4444** [comment]
yes because my some created_ats are empty but its better to take it null-safety

**Comment by shayan-yousefi** [comment]
the commit c4fc3a136e36 solved the issue.
