### ISSUE TITLE
Styling issue

### ISSUE THREAD

**Issue by RealMrHex** [shayan100/IraninaDatePicker-filament#4]
![image](https://user-images.githubusercontent.com/62525184/234174121-0ad08a39-d7a4-49ab-83e4-aabb2ff632a3.png)

Can you fix the styles please?
Border and Focus styles are not matched with the default style system.

**Comment by RealMrHex** [comment]
These classes must be applied to the input
```css
block w-full transition duration-75 rounded-lg shadow-sm 
outline-none focus:border-primary-500 focus:ring-1 focus:ring-inset 
focus:ring-primary-500 disabled:opacity-70 dark:bg-gray-700 
dark:text-white dark:focus:border-primary-500 border-gray-300 dark:border-gray-600
```
Thanks for your time

**Comment by shayan-yousefi** [comment]
hi @RealMrHex
thank you for telling this issue.
the commit a5db040249b6594 solved the issue.
